services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: SomeGoodPassword!
      MSSQL_PID: Evaluation
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data: